NumPy  
Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of functions to operate on these arrays.
NumPy arrays are the core data structure in NumPy. They are similar to Python lists, but are more efficient and flexible. NumPy arrays can be used to represent vectors, matrices, and higher -dimensional arrays.  
NumPy arrays have several advantages over Python lists, including:   
*   Faster performance: NumPy arrays are implemented in C, which makes them faster than Python lists  
*   More memory efficient: NumPy arrays use less memory than Python lists  
*   More flexible: NumPy arrays can be used to represent vectors, matrices, and higher-dimensional arrays, while Python lists are limited to one-dimensional arrays  
 NumPy arrays can be created using the numpy.array() function, which takes a Python list or other  
 iterable as input and returns a NumPy array.

In [ ]:
#NumPy is a general purpose array processing package
#Numpy is binding with C/C++ libraries so it is very fast , very efficient and can be used in many areas of scientific computing


In [1]:
import numpy as np

In [4]:
lst=[1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [3]:
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [8]:
arr.shape
#gives number of row, number of column

(5,)

In [21]:
lst1=[1,2,3,4,5]
lst2=[6,7,8,9,10]
lst3=[11,12,13,14,15]

arr1=np.array([lst1,lst2,lst3])
arr1
arr1.shape

arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [24]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
arr1[0:2,1:3]


array([[2, 3],
       [7, 8]])

In [28]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [30]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
#broadcasting 
arr[3:]=100
arr

array([  0,   2,   4, 100, 100])

In [ ]:
#WHY copy function
arr2=arr
arr2
arr2[3:]=500
#arr2
arr

#arr also got updated with 500 when we didnt change it because bith point to same references - array is reference type. So when we change arr2, arr also gets updated
#because they both point to same memory location. So we need to make a copy of arr to arr2 to avoid this.  We use COPY FUNCTION

array([  0,   2,   4, 500, 500])

In [48]:
arr2=arr.copy()
arr2[3:]=1000
arr2

array([   0,    2,    4, 1000, 1000])

In [ ]:
arr

#Now as we used copy fucntion it did not get referenced and now arr is not updated when i change arr2

array([  0,   2,   4, 500, 500])